language: go
go:
  - '1.9'

services:
  - docker

before_install:
  - wget https://kubernetes-helm.storage.googleapis.com/helm-v2.6.1-linux-amd64.tar.gz
  - tar xzf helm-v2.6.1-linux-amd64.tar.gz

install:
  - go get

script:
  - go vet
  - gofmt -e -d *.go
  - go build
  - linux-amd64/helm lint ./chart/stack2slack

after_success:
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
